Use ENS name as account identifier if it exists
hop-protocol/hop pull request #319
Opened 2021-12-12 08:12 UTC by jackmpcollins

Show ENS name instead of truncated address in transactions pill if one exists for the address.

Before
<img width="476" alt="Screen Shot 2021-12-12 at 12 04 05 AM" src="https://user-images.githubusercontent.com/6640905/145705101-6f474a0b-9225-4507-b31f-2f6257e9bc58.png">

After
<img width="490" alt="Screen Shot 2021-12-12 at 12 03 50 AM" src="https://user-images.githubusercontent.com/6640905/145705105-30e56d55-56c5-4f9d-8ae4-722c2db40f0e.png">

2021-12-14 07:36 UTC, kangarang requested changes
hi @jackmpcollins, thanks for this pr. currently, these changes will only work if the user is connected to ethereum mainnet. ideally, we should display the user's ens name regardless of connected network. instead of using the connected provider, i recommend grabbing the mainnet provider via the util [`getProviderByNetworkName('ethereum')`](https://github.com/hop-protocol/hop/blob/develop/packages/frontend/src/utils/getProvider.ts#L17) and using that to resolve the ens name.

2021-12-14 07:36 UTC, kangarang commented on packages/frontend/src/components/header/TxPill.tsx
> +import { ethers } from 'ethers';
i believe this line can be removed (extraneous)

2021-12-14 07:36 UTC, kangarang commented on packages/frontend/src/components/header/TxPill.tsx
> +  })
add useEffect dependencies `[address, provider]`

2021-12-15 07:31 UTC, jackmpcollins commented
Thanks for the review @kangarang . Updated now.

2021-12-16 01:34 UTC, kangarang approved these changes
LGTM. thanks again for your contribution @jackmpcollins

2021-12-16 01:34 UTC, merged