Feat/add reencrypt keystore
hop-protocol/hop pull request #372
Opened 2022-01-07 23:04 UTC by shanefontaine

* Add ability to `reencrypt` keystores
* Only major change is that a custom file path needs to be explicitly passed in with `—path` instead of `args[1]`. I did this because I didn’t think it was possible for a user to know that `args[1]` should be the path, but happy to revert to what it was if you think otherwise.
* DRYed some logic that is now re-used b/c of new command

2022-01-09 02:01 UTC, miguelmota requested changes

2022-01-09 02:10 UTC, miguelmota commented
The reencryption works great

Some minor bugs

Issue 1:
Expected: Throw error after entering invalid current passphrase and not proceed to enter new passphrase
Actual: No error was thrown when entering invalid current passphrase and it proceeded to prompt for new passphrase

![DeepinScreenshot_select-area_20220108175957](https://user-images.githubusercontent.com/168240/148666332-3432e8cf-766f-4038-b9b2-cc3d5921f661.png)

Issue 2:
Expected: Screen to not clear after reencrypting new passphrase.
Actual: Screen cleared after rencrypting new passphrase. 

![DeepinScreenshot_select-area_20220108180110](https://user-images.githubusercontent.com/168240/148666364-41184c17-d4ec-4334-a6cc-12849dd0ba90.png)

I think the screen should only clear when showing the mnemonic. The screen should not clear when reencrypting. It should not show the 'press enter to exit' prompt.  It should only show the 'reencryption is complete' log and behave similar to decrypt command.

2022-01-09 17:03 UTC, shanefontaine commented on packages/hop-node/src/cli/keystores.ts
> +  const actionOptions = [
Resolved with ef6b0199ea112dd3eeddab2e1ac0ea575adb2fda

2022-01-09 17:03 UTC, shanefontaine commented
I agree with all comments. They've been resolved in ef6b0199ea112dd3eeddab2e1ac0ea575adb2fda. Docs have been updated.

2022-01-10 19:30 UTC, miguelmota commented
@shanefontaine the updates work great 👍

2022-01-10 19:30 UTC, miguelmota approved these changes

2022-01-10 19:37 UTC, merged