hop-node: SyncWatcher: Add handler for WithdrawalBondSettled event. #334
hop-protocol/hop pull request #380
Opened 2022-01-20 05:20 UTC by miguelmota

- Addresses https://github.com/hop-protocol/hop/issues/334
- Adds pure handler for `WithdrawalBondSettled` event
- Adds "populate" handler for reading async data to fully process `WithdrawalBondSettled` event

2022-01-26 23:25 UTC, shanefontaine requested changes
**_Please do not merge this until the Polygon messaging is resolved and has been pushed to the bonders. I think we should be aware that when we push these to bonders they will take time (~1 hour?) to sync because they will need to look back all the way for this new event._**

* Since a `transferId` can be settled either with `settleBondedWithdrawal()` OR `settleBondedWithdrawals()`, we need to keep the event handlers a little more in sync. For example we need to get the `amount` from the calldata in `handleWithdrawalBondSettledEvent()` and add it to the DB value `multipleWithdrawalsSettledTotalAmount` so that the value stays in sync (related, there is currently a bug in `handleMultipleWithdrawalsSettled()` overwriting the `amount` in #333 ). More information about the `amount` storing here can be found in the first bullet point of #334 ).

* I believe the changes in the `TransfersDb` should be made in the `TransferRootsDb` instead. In theory, this event deals with settling a root, not a transfer. Because of this, `withdrawalBondSettledTxHash` should live in the `TransferRootsDb`, similar to `multipleWithdrawalsSettledTxHash`. It would also need to become an array in order to not overwrite items, since there can be many per root.

With all that said I think #333 and #334 should be handled in this PR, as they are tightly coupled. Let me know if this all makes sense.

2022-01-27 01:56 UTC, miguelmota commented on packages/hop-node/src/watchers/SyncWatcher.ts
> +    const allSettled = this.getIsDbTransfersAllSettled(dbTransfers)
No that is not how the queue works. Any `await db.transfers.update(...)` update call will only resolve once it has been written to disk, so it's not possible to make an update and then have subsequent db gets return outdated data. Any db gets will return the most up to date data as long as db updates are awaited

2022-01-27 02:10 UTC, miguelmota commented
>  Since a `transferId` can be settled either with `settleBondedWithdrawal()` OR `settleBondedWithdrawals()`, we need to keep the event handlers a little more in sync. For example we need to get the `amount` from the calldata in `handleWithdrawalBondSettledEvent()` and add it to the DB value `multipleWithdrawalsSettledTotalAmount` so that the value stays in sync (related, there is currently a bug in `handleMultipleWithdrawalsSettled()` overwriting the `amount` in #333 ). More information about the `amount` storing here can be found in the first bullet point of #334 ).

First question, why aren't `Withdrew` event amounts added to `multipleWithdrawalsSettledTotalAmount` but `WithdrawalBondSettled` should be added?

Second question, I don't like the idea of adding the amount to an existing db value because it makes the update be stateful and it's possible that it can be double counted. My preference is to track it separately and compute them when we need the total. Do you have thoughts on this suggestion?

>    I believe the changes in the `TransfersDb` should be made in the `TransferRootsDb` instead. In theory, this event deals with settling a root, not a transfer. Because of this, `withdrawalBondSettledTxHash` should live in the `TransferRootsDb`, similar to `multipleWithdrawalsSettledTxHash`. It would also need to become an array in order to not overwrite items, since there can be many per root.

I don't like the idea of having an array because then we need to iterate over it to make sure we don't double add it. The only array we have in the db entries are for transferIds but that's because it's an simple atomic string array. My preference is to keep it in the transfersDb for this reason.

> With all that said I think #333 and #334 should be handled in this PR, as they are tightly coupled. Let me know if this all makes sense.

Since the scope of this PR is to track `WithdrawalBondSettled` events, I think the separate issue #333 should be handled separately to not introduce too much complexity in a PR

2022-01-27 06:10 UTC, shanefontaine commented
> First question, why aren't Withdrew event amounts added to multipleWithdrawalsSettledTotalAmount but WithdrawalBondSettled should be added?

Transfers that are withdrawn are not bonded, so their amounts are never settled and shouldn't be added to the settle amount. It is accounted for [by marking the transfer as `isBondable = false` in the `handleWithdrewEvent()`](https://github.com/hop-protocol/hop/blob/c72e40864cf2b7d31213fd3fe380736855d1c55d/packages/hop-node/src/watchers/SyncWatcher.ts#L475) and is checked in [`getIsDbTransfersAllSettled()`](https://github.com/hop-protocol/hop/blob/c72e40864cf2b7d31213fd3fe380736855d1c55d/packages/hop-node/src/watchers/SyncWatcher.ts#L1421).

> Second question, I don't like the idea of adding the amount to an existing db value because it makes the update be stateful and it's possible that it can be double counted. My preference is to track it separately and compute them when we need the total. Do you have thoughts on this suggestion?

I think that is a great suggestion. I like that a lot 👍 

> I don't like the idea of having an array because then we need to iterate over it to make sure we don't double add it. The only array we have in the db entries are for transferIds but that's because it's an simple atomic string array. My preference is to keep it in the transfersDb for this reason.

That is a great point and something I never considered. I think that makes sense if we also move the `multipleWithdrawalsSettledTxHash` to the `TransfersDb` as well, as we have the same overwriting issue there (there can be many values for `multipleWithdrawalsSettledTxHash` because it can be called many times). I think it is worth speaking through how to think about `settleBondedWithdrawal()` and `settleBondedWithdrawals()`, as they should be kept together (they perform the same task), but this will break our current mental model.

> Since the scope of this PR is to track WithdrawalBondSettled events, I think the separate issue #333 should be handled separately to not introduce too much complexity in a PR

Understood and agreed.

2022-03-29 03:03 UTC, miguelmota commented on packages/hop-node/src/watchers/SyncWatcher.ts
> +        .then(async () => {
Resolved by https://github.com/hop-protocol/hop/pull/380/commits/a1987e7521d13f9b62ae5aba9879a52e056b4f06

2022-03-29 03:03 UTC, miguelmota commented on packages/hop-node/src/watchers/SyncWatcher.ts
> +    if (!dbTransferRoot) {
Resolved by https://github.com/hop-protocol/hop/pull/380/commits/fec874f663859403a39227325428bc2bda778dc8

2022-03-29 03:03 UTC, miguelmota commented on packages/hop-node/src/watchers/SyncWatcher.ts
> +
Resolved by https://github.com/hop-protocol/hop/pull/380/commits/fec874f663859403a39227325428bc2bda778dc8

2022-03-29 03:05 UTC, miguelmota commented
Ready for review

the initial comment has been updated with updates made

2022-03-29 21:22 UTC, shanefontaine reviewed
Looks good!

* I believe the bonders could take an hour or more to start syncing after this update because they need to look back to the start of the bridge for the new event. Do we have a plan to "pre-sync" this data or something like that?
* Does there need to be a DB migration to populate the `MultipleWithdrawalsSetteld` DB?

2022-03-29 21:22 UTC, shanefontaine commented on packages/hop-node/src/db/TransferRootsDb.ts
> +      return item.multipleWithdrawalsSettledTotalAmount
Technically this will be incorrect if a root is re-settled, which is true even with the current code. Will that be a problem at all here?

2022-03-29 21:22 UTC, shanefontaine commented on packages/hop-node/src/db/TransferRootsDb.ts
> +      return item.multipleWithdrawalsSettledTxHash
Same comment as above

2022-03-30 03:27 UTC, miguelmota commented on packages/hop-node/src/db/TransferRootsDb.ts
> +      return item.multipleWithdrawalsSettledTxHash
Resolved by https://github.com/hop-protocol/hop/pull/380/commits/a16b7acc1151b71ef3415c05e915910633cd03c1

2022-03-30 03:27 UTC, miguelmota commented on packages/hop-node/src/db/TransferRootsDb.ts
> +      return item.multipleWithdrawalsSettledTotalAmount
Resolved by https://github.com/hop-protocol/hop/pull/380/commits/a16b7acc1151b71ef3415c05e915910633cd03c1

2022-03-31 00:18 UTC, miguelmota commented
1. I think we can run a parallel instance to sync the new events and then switch over the db (as we discussed)
2. migration has been added to force sync all MultipleWithdrawalsSettled events

2022-04-12 03:10 UTC, merged