Add support for Gnosis-Safe as a safe-app.
hop-protocol/hop pull request #395
Opened 2022-02-16 14:17 UTC by nicosampler

How to test it:

1. Go to any gnosis safe. Make sure that your wallet is in the same network as your safe. Also, your wallet has to be using an account that is the owner of the safe. 
2. go to `Apps` section
3. add custom app. for testing purposes, you can use this link [hop-nicosampler.vercel.app](https://hop-nicosampler.vercel.app/)
5. enjoy 🎉 

Disclaimer: There is a little problem, when the swap is made, the HOP Dapp is not realizing it was completed. Perhaps it's a problem related with gnosis chain, where I tested it.

2022-02-25 19:09 UTC, kangarang requested changes
this is shaping up nicely. just 1 more copy edit and we should be good to merge. thanks again for your contribution @nicosampler

2022-02-25 19:09 UTC, kangarang commented on packages/frontend/src/hooks/useIsSmartContractWallet.ts
> +      setIsSmartContractWallet(!code || code !== '0x');
is there a case that `code` will be falsy here? (i.e. an empty string). if not, i think we can simply this for readability

```suggestion
      setIsSmartContractWallet(code !== '0x');
```

2022-02-25 19:09 UTC, kangarang commented on packages/frontend/src/pages/Send/Send.tsx
> +            ? `You are connecting with a smart contract wallet, may be the case you don't own the same address on the destination network. Proceed with caution!`
Let's change this copy to:

`The connected account is detected to be a smart contract wallet. Please provide a custom recipient to proceed with this transaction.`

2022-02-25 23:47 UTC, nicosampler commented on packages/frontend/src/pages/Send/Send.tsx
> +            ? `You are connecting with a smart contract wallet, may be the case you don't own the same address on the destination network. Proceed with caution!`
done!

2022-02-28 21:30 UTC, kangarang approved these changes
@nicosampler, LGTM.

great job on this pr, and thanks again for your contribution!

2022-02-28 21:32 UTC, merged