hop-node: BondWithdrawalWatcher: Check bond amount doesn't exceed available amount on source chain. #409
hop-protocol/hop pull request #413
Opened 2022-03-18 00:23 UTC by miguelmota

2022-03-18 02:00 UTC, kangarang approved these changes
LGTM

2022-03-18 02:00 UTC, kangarang commented on packages/hop-node/src/watchers/BondWithdrawalWatcher.ts
> +      const pendingAmount = await sourceL2Bridge.getPendingAmountForChainId(destinationChainId!)
non-blocking: is `destinationChainId` *always* defined at this point? if so, we should improve the various `Transfer` types in `TransfersDb.ts`

2022-03-18 02:00 UTC, kangarang commented on packages/hop-node/src/watchers/BondWithdrawalWatcher.ts
> +      if (amount!.gt(hTokensAvailable)) {
same comment as above -- if `amount` is defined here, our types could be improved. again, this is non-blocking

2022-03-18 05:43 UTC, miguelmota commented on packages/hop-node/src/watchers/BondWithdrawalWatcher.ts
> +      const pendingAmount = await sourceL2Bridge.getPendingAmountForChainId(destinationChainId!)
good point, the db getters can be updated to return specific types. I'll address this in another PR since the changes will affect many other places

2022-03-23 17:48 UTC, miguelmota commented
@shanefontaine going to merge this if you think it looks good

2022-03-23 17:53 UTC, shanefontaine commented
@miguelmota I think this would not work in the case where a malicious person can mint unlimited hTokens (i.e. if the chain has a bug in it).

Because of this, we would need to check the `chainBalance` from L1 along with the pending amount, and possibly other items as well.

2022-03-23 18:06 UTC, miguelmota commented
checking L1 balance makes sense now

so instead of

_transferAmount <= sourceChainBridgeHTokenBalance + pendingAmountFromSourceToDestination_

it should be

_transferAmount <= l1BridgeBalance - pendingAmountFromSourceToDestination_

is this correct?

2022-04-13 16:26 UTC, miguelmota commented
Ready for review

2022-08-04 20:11 UTC, shanefontaine requested changes
I believe this does not track in-flight items that are neither part of `chainBalance` nor `pendingAmount`. Do you remember talking about this and if there was any conclusion here?

2022-08-04 20:11 UTC, shanefontaine commented on packages/hop-node/src/watchers/BondWithdrawalWatcher.ts
> +      const isFromNonRollup = [Chain.Polygon, Chain.Gnosis].includes(sourceChain)
This should apply to every chain, so the concept of `isFromNonRollup` is unnecessary here.

2024-01-19 17:33 UTC, closed without merging

2024-01-19 17:33 UTC, miguelmota commented
Closing as stale